### ISSUE TITLE
Can i some how work not with .minute.csv but smth like 30sec.csv, or smth?

### ISSUE THREAD

**Issue by youbrain** [zelos-alpha/demeter#10]
i can change code of demeter-fetch to download 30sec/row data, but dont know is there any way to work with such file with demeter

**Comment by 32ethers** [comment]
Based on our experience in statistical work, if you seek precise results, it's preferable to replay each log individually. However, this requires re-implementing contract code in Python, which can significantly slow down the backtesting process.

Furthermore, it's not easy to modify the time intervals in Demeter. In subsequent versions, some markets may have hourly time intervals.

If you really want to create your own 30-second version, you need to pay attention to Uniswap/data.py, as it involves resampling data. However, I don't believe this will significantly improve accuracy.
