### ISSUE TITLE
Making Demeter version dependencies more flexible

### ISSUE THREAD

**Issue by miohtama** [zelos-alpha/demeter#16]
Currently `setup.py` declares versions in absolute manner:

```
    install_requires=[
        "numpy==1.26.4",
        "pandas==2.2.0",
        "python-dateutil==2.9.0.post0",
        "pytz==2024.1",
        "six==1.16.0",
        "db-dtypes==1.2.0",
        "tqdm==4.66.2",
        "orjson==3.9.15",
    ],
```

This makes it impossible to use Demeter with any other Python package that is using the same dependencies, but likely with slightly different minor versions. [Read more about the issue here](https://stackoverflow.com/a/44938662/315168)

My suggestion is that all of these should be changed:

```
    install_requires=[
        "numpy>=1.26.4",
        "pandas>=2.2.0",
        "python-dateutil>=2.9.0.post0",
        "pytz>=2024.1",
        "six>=1.16.0",
        "db-dtypes>=1.2.0",
        "tqdm>=4.66.2",
        "orjson>=3.9.15",
    ],
```

(Or even more flexible ones).

The process would be

- Update `setup.py`
- Rerun `pip freeze` or any other commands needed to upgrade the package (where is this process documented, referred?)
- Run test suite
- Release new Demeter version to PyPi

After this, installing Demeter with other Python packages because possible and much easier.

**Comment by 32ethers** [comment]
Thanks for your help, I will update and release a new version,
