### ISSUE TITLE
position changes before the price enters the position range

### ISSUE THREAD

**Issue by colinleefish** [zelos-alpha/demeter#17]
Hi. I'm using your framework to work on a "grid strategy", where I created multiple positions and was about to manipulate them under some circumstances.

I encountered strange behaviors of some positions: when the price is moving towards the position but hasn't entered it, the amount of token pairs changes.

For example, below are some position with liquidities in it, below the price are quote and above the price are the base token. the price is going up but hasn't reached a position.

however, the balance has changed as if some of the base token is traded into the quote token.

```
-----------------------------------------------------------------------------------------------------------------------------------------------------------
quote:      0.000, base:      0.799, quote pending:      0.000, base pending:      0.000, value:   2578.968, grid_lower:   3276.667, grid_upper:   3291.667
-----------------------------------------------------------------------------------------------------------------------------------------------------------
quote:      0.000, base:      0.799, quote pending:      0.000, base pending:      0.000, value:   2578.968, grid_lower:   3261.190, grid_upper:   3276.190
-----------------------------------------------------------------------------------------------------------------------------------------------------------
quote:      0.000, base:      0.799, quote pending:      0.000, base pending:      0.000, value:   2578.968, grid_lower:   3245.714, grid_upper:   3260.714
-----------------------------------------------------------------------------------------------------------------------------------------------------------
quote:     51.640, base:      0.783, quote pending:      1.074, base pending:      0.000, value:   2581.086, grid_lower:   3230.238, grid_upper:   3245.238 <----price hasn't been here yet
-----------------------------------------------------------------------------------------------------------------------------------------------------------
quote:      0.000, base:      0.000, quote pending:      0.000, base pending:      0.000, value:      0.000, grid_lower:   3214.762, grid_upper:   3229.762  3229.552 10.0
-----------------------------------------------------------------------------------------------------------------------------------------------------------
quote:   2616.318, base:      0.000, quote pending:      0.000, base pending:      0.000, value:   2616.318, grid_lower:   3199.286, grid_upper:   3214.286
-----------------------------------------------------------------------------------------------------------------------------------------------------------
quote:   2835.162, base:      0.000, quote pending:      0.000, base pending:      0.000, value:   2835.162, grid_lower:   3183.810, grid_upper:   3198.810
-----------------------------------------------------------------------------------------------------------------------------------------------------------
quote:   2365.065, base:      0.000, quote pending:      4.704, base pending:      0.002, value:   2374.624, grid_lower:   3168.333, grid_upper:   3183.333
```

Could you provide insight into what might be causing the problem? Thank you very much.

**Comment by 32ethers** [comment]
Please check if I understand correctly: the current price hasn't entered the position's price range, but the fees have already started to accumulate, right? Could you provide the backtest time period and specify when the issue occurred? That's odd because current price is very far from position price range.

**Comment by colinleefish** [comment]
Sure thing, here are the details.

[chain and ca]
`ethereum-0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640` (USDC/ETH)

[the exact time]
2024-11-10 17:42:00

[price at moment]
3229.552

[the position of interest]

lower_quote_price = 3230.238
upper_quote_price = 3245.238
quote_add = 0
base_add = 0.799


> Please check if I understand correctly: the current price hasn't entered the position's price range, but the fees have already started to accumulate, right? Could you provide the backtest time period and specify when the issue occurred? That's odd because current price is very far from position price range.

**Comment by 32ethers** [comment]
so the price is very close to your position range. 

This could happen, because we allocate fees based on ticks. The price represented by a tick is different from the regular price; it has lower precision. This causes two issues 

1. When adding liquidity, the liquidity needs to be allocated to the corresponding tick based on the tick spacing. For example, in a pool with a 0.05% fee, if the tick spacing is 10, and you want to add liquidity at tick 200005, you can only add it to tick 200000 or 200010. This causes a slight discrepancy between the range you intended to add liquidity at (based on the regular price) and the actual range.
2. If the price difference is very small, their ticks might be the same.

Additionally, if the price fluctuates at the edge of the position, a portion of the fees will be allocated proportionally.

I hope this answer is helpful to you.

**Comment by colinleefish** [comment]
> so the price is very close to your position range.
> 
> This could happen, because we allocate fees based on ticks. The price represented by a tick is different from the regular price; it has lower precision. This causes two issues
> 
> 1. When adding liquidity, the liquidity needs to be allocated to the corresponding tick based on the tick spacing. For example, in a pool with a 0.05% fee, if the tick spacing is 10, and you want to add liquidity at tick 200005, you can only add it to tick 200000 or 200010. This causes a slight discrepancy between the range you intended to add liquidity at (based on the regular price) and the actual range.
> 2. If the price difference is very small, their ticks might be the same.
> 
> Additionally, if the price fluctuates at the edge of the position, a portion of the fees will be allocated proportionally.
> 
> I hope this answer is helpful to you.

Oh I see. Thanks for clearing that up! I really appreciate it.
