### ISSUE TITLE
Add 'price' field in the output JSON for add_liquidity and remove_liquidity action types

### ISSUE THREAD

**Issue by vinayyak** [zelos-alpha/demeter#5]
Hi, when I run the backtest for a USDC/ETH pool, the output JSON & CSV shows me buy and sell transactions with a 'price' field in the block but this field is not present in the add or remove liquidity action type blocks in the JSON. Would be great if this could be added so it can be tracked what the price of ETH was when the add or remove liquidity action type was triggered. Tried doing this myself by editing the Actuator class but did not succeed.

**Comment by 32ethers** [comment]
Acutally we have notify function in Strategy class, where you can get read and write actions when it was throwed. 

So you can write a strategy like this 

```python
class DemoStrategy(Strategy):
    def initialize(self):
        new_trigger = AtTimeTrigger(time=datetime(2023, 8, 15, 12, 0, 0), do=self.add_liq)
        self.triggers.append(new_trigger)

    def add_liq(self, row_data: RowData):
        lp_market: UniLpMarket = self.markets[market_key]
        new_position, amount0_used, amount1_used, liquidity = lp_market.add_liquidity(1000, 4000)

    def notify(self, action: BaseAction):
        """
        When a new action(add/remove liquidity) is executed, you can be notified by this call back.
        """
        # add price to actions, so price will be kept in csv file. 
        action.price = "{:.3f}".format(actuator.token_prices.loc[action.timestamp][eth.name])
        pass


```

here action get a new attribute "price", as python pass object by reference, this  attribute will be kept and write to csv

**Comment by vinayyak** [comment]
Hi, Thanks for your help and reply, tried out the notify function and it worked for JSON but the price did not show up in the CSV. I think it might be related to the `save_result` method from the `Actuator` Class: 
```

**Comment by 32ethers** [comment]
Oops, actually csv and json are two different things. 

csv keeps asset change. such as net_value, etc. 

but json and pkl keeps all actions. such as add liquidity, collect. Action class has differenet attributes. so it would be a mass if kept in csv

If you want keep price in account status list, just call get_account_status_dataframe(some name like this, and easy to find), then you get a dataframe object. and you can append a price column on it. 
Price dataframe and account_status_dataframe have the same timestamp index. so it's very simple to append the price.

then you call dataframe.to_csv(), this csv will contain price

**Comment by vinayyak** [comment]
Yup, I was reading the Actuator code today again and also figured that the CSV was printing the account status and the JSON was printing the action list. Will implement the tips you have given to get the price into the DataFrame. Thanks for your help again @32ethers Great Library, Cheers!
